### ISSUE TITLE
Question: Using the API package provided by elastic/go-elasticsearch

### ISSUE THREAD

**Issue by karmi** [procore/nox#3]
Hello,

I'm curious about implementing the Elasticsearch APIs, like `ClusterState()` in:

https://github.com/procore/nox/blob/4cf2e1f0f59e852da66c7e8ff6ffe43c1f27dc25/internal/elastic/cluster.go#L19

The [official client](https://github.com/elastic/go-elasticsearch) provides the `esapi` package, which can be used standalone, although it's main usage is in the official client itself; see documentation https://github.com/elastic/go-elasticsearch/blob/master/esapi/doc.go.

This could decrease the amount of API implementations you have to do it in the library, and you can use a different HTTP client, if you would wish to.

**Comment by maxine-krebs** [comment]
That is a good question, Thanks for asking. I thought about plugging into the official ES client but in the past we've needed to support some specific use cases that are not covered by the official package. Also, where I'd like to take `nox` in the future, I would prefer to keep control of the whole communication process.

**Comment by karmi** [comment]
Understood.

> (...) in the past we've needed to support some specific use cases that are not covered by the official package.

I'm curious about this part. If you would ever find time to report those in the `elastic/go-elasticsearch` repository, I'd be grateful.
